# Site settings
title: 伊一小站
baseurl: "" 
url: "http://qijunxin.github.io" 
description: 齐俊鑫个人博客
avatar: /img/avatar.jpg
permalink: /:year/:month/:day/:title/

# other links
github_username: qijunxin
email: 1531211307@qq.com
weibo_username: qijunxin


# comments
disqus_shortname: qijunxin

# statistic analysis 
baidu_tongji_id: ee94b48528a1796da91f8c0c193a73f3
google_analytics_id: 

# Build settings
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge

# url
category_dir: category/
tag_dir: tag/

# excerpt
excerpt_separator: "\n\n\n\n"

# paginate
gems: [jekyll-paginate]
paginate: 5
